import { findScenario, ITEMS, SCENARIOS } from "./content/scenarios";
import type { Choice, GameState, StatKey } from "./types";
const initialInventory = Object.fromEntries(ITEMS.map((item) => [item.id, item.count]));
export const initialState = (): GameState => ({ phase: "reading", scenarioId: SCENARIOS[0].id, stats: { hp: 72, maxHp: 100, strength: 1, agility: 1, willpower: 1, storySense: 0 }, coins: 8, inventory: initialInventory, history: [{ day: 0, text: "The world became a scenario.", tone: "neutral" }], sponsorLog: [{ label: "THE AUDIENCE", text: "A new story has begun.", tone: "watch" }] });
export function isChoiceLocked(choice: Choice, state: GameState) { return choice.requirement ? state.stats[choice.requirement.stat] < choice.requirement.min : false; }
export function useItem(state: GameState, id: string): GameState { if ((state.inventory[id] ?? 0) <= 0 || state.phase === "win" || state.phase === "lose") return state; const inventory = { ...state.inventory, [id]: state.inventory[id] - 1 }; if (id === "ration") return { ...state, inventory, stats: { ...state.stats, hp: Math.min(state.stats.maxHp, state.stats.hp + 10) }, lastOutcome: { text: "You eat in three careful bites. The warmth is almost a memory.", reward: "HP +10", tone: "good" } }; if (id === "lens") return { ...state, inventory, stats: { ...state.stats, storySense: state.stats.storySense + 1 }, lastOutcome: { text: "The lens catches a thread of light around the hidden choice.", reward: "Story Sense +1", tone: "good" } }; return { ...state, inventory, stats: { ...state.stats, hp: Math.min(state.stats.maxHp, state.stats.hp + 6) }, lastOutcome: { text: "The charm grows warm. Something else takes the edge of the wound.", reward: "HP +6", tone: "good" } }; }
export function beginChoices(state: GameState): GameState { return { ...state, phase: "choice", lastOutcome: undefined }; }
export function resolveChoice(state: GameState, choice: Choice): GameState { if (state.phase !== "choice" || isChoiceLocked(choice, state)) return state; const d = choice.statDelta ?? {}; const stats = { ...state.stats, hp: Math.max(0, Math.min(state.stats.maxHp, state.stats.hp + (d.hp ?? 0))), strength: Math.max(0, Math.min(9, state.stats.strength + (d.strength ?? 0))), agility: Math.max(0, Math.min(9, state.stats.agility + (d.agility ?? 0))), willpower: Math.max(0, Math.min(9, state.stats.willpower + (d.willpower ?? 0))), storySense: Math.max(0, Math.min(9, state.stats.storySense + (d.storySense ?? 0))) }; const scenario = findScenario(state.scenarioId); const nextPhase: GameState["phase"] = choice.next === "win" ? "win" : choice.next === "lose" || stats.hp <= 0 ? "lose" : "between"; const inventory = { ...state.inventory }; if (choice.itemGain) inventory[choice.itemGain] = (inventory[choice.itemGain] ?? 0) + 1; const outcome = choice.outcome ?? choice.title; const outcomeTone: "good" | "bad" = nextPhase === "lose" ? "bad" : "good"; const history: GameState["history"] = [{ day: scenario.day, text: outcome, tone: outcomeTone }, ...state.history].slice(0, 5); const sponsorTone: "watch" | "approve" = choice.tone === "safe" ? "watch" : "approve"; const sponsorLog: GameState["sponsorLog"] = choice.sponsor ? [{ label: "SPONSOR SIGNAL", text: choice.sponsor, tone: sponsorTone }, ...state.sponsorLog].slice(0, 5) : state.sponsorLog; return { ...state, stats, coins: Math.max(0, state.coins + (d.coins ?? 0)), inventory, phase: nextPhase, scenarioId: nextPhase === "between" ? choice.next : state.scenarioId, selectedChoice: choice.id, lastOutcome: { text: outcome, reward: choice.reward, tone: outcomeTone }, history, sponsorLog }; }
export function continueRun(state: GameState): GameState { return state.phase === "between" ? { ...state, phase: "reading", lastOutcome: undefined, selectedChoice: undefined } : state; }
export function restartRun(): GameState { return initialState(); }
export const statLabel = (key: StatKey) => ({ strength: "Strength", agility: "Agility", willpower: "Willpower", storySense: "Story Sense" })[key];
